name: build_umn_iptv

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build_apk_umn_ota_iptv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "oracle"
          cache: gradle

      - name: Setup gradle properties
        run: |
          ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
          sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
          cat gradle.properties
          
#      - name: Gradle cache
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute gradlew
        run: chmod +x gradlew

#      - name: assembleDebug
#        run: |
#          ./gradlew clean :examples:umn-iptv:assembleDebug
#
#      - name: Uploading apk debug
#        uses: actions/upload-artifact@v4
#        with:
#          name: apk-debug
#          path: examples/umn-iptv/build/outputs/apk/debug/umn-iptv-debug.apk

      - name: assembleRelease
        run: |
          ./gradlew clean :examples:umn-iptv:assembleRelease

      - name: Uploading apk release
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: examples/umn-iptv/build/outputs/apk/release/umn-iptv-release.apk