name: publish_to_maven_local

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  publish_to_maven_local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute gradlew
        run: chmod +x gradlew

      - name: Publish to maven local
        run: |
          ./gradlew clean build
          ./gradlew clean publishToMavenLocal

      - name: Create a module archive
        run: cd ~ && tar czvf /tmp/id.xxx.module.tar.gz .m2/repository/id/xxx/module

      - name: Uploading a module archive
        uses: actions/upload-artifact@v2
        with:
          name: module
          path: /tmp/id.xxx.module.tar.gz